version: '3'
services:
  geth:
    container_name: geth.local
    build:
      context: "."
      dockerfile: "docker/geth/Dockerfile"
    ports: 
      - "8545:8545"
      - "30303:30303"
    volumes:
      # - "./docker/geth/data:/home/geth/data"
      - "./docker/geth/config:/home/geth/config"
      - "./docker/keystore:/home/geth/keystore"
    command: --datadir /home/geth/data --keystore /home/geth/keystore --allow-insecure-unlock --unlock 0x1bb90cde8a032cb4963813a5b4db4981afa5b9c6 --networkid 99 --lightkdf --nodiscover --maxpeers=0 --port=0 --nousb --ipcdisable --mine --miner.threads 1 --miner.etherbase 0x1bb90cde8a032cb4963813a5b4db4981afa5b9c6 --http --http.port 8545 --http.api admin,personal,eth,miner,debug,txpool,net,web3 --http.addr 0.0.0.0 --http.corsdomain * --http.vhosts * --password=/home/geth/keystore/password
  deployer:
    build:
      context: "."
      dockerfile: "docker/deployer/Dockerfile"
    volumes:
      - "./docker/geth/bin/:/root/bin"
    command: ["median-deploy", "BATUSD", "BTCUSD", "ETHUSD", "KNCUSD", "MANAUSD", "0x1bb90cde8a032cb4963813a5b4db4981afa5b9c6"]
  ssb_client:
    build:
      context: "."
      dockerfile: "docker/ssb-server/Dockerfile"
    volumes:
      - "./docker/ssb-server/config/client.json:/root/.ssb/config"
    command: ["/bin/sh"]
  ssb_server:
    container_name: ssb.local
    build:
      context: "."
      dockerfile: "docker/ssb-server/Dockerfile"
    ports:
      - "8008:8008"
    volumes:
      - "./docker/ssb-server/config/server.json:/root/.ssb/config"
  omnia_feed:
    depends_on:
      - spire
    build:
      context: "."
      dockerfile: "docker/omnia/Dockerfile"
    volumes:
      - "./lib:/home/omnia/lib"
      - "./test:/home/omnia/test"
      - "./docker/spire/config/client.json:/home/omnia/spire.json"
      - "./docker/ssb-server/config/client.json:/home/omnia/.ssb/config"
  spire:
    image: chroniclelabs/spire:latest
    container_name: spire.local
    ports:
      - "9100:9100"
    command: ["-c", "/root/spire.json", "agent"]
    volumes:
      - "./docker/keystore:/root/keystore"
      - "./docker/spire/config/agent.json:/root/spire.json"
