version: '3'
services:
  gofer:
    container_name: gofer.local
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    entrypoint: [ "/usr/local/bin/gofer" ]
    command: [ "-c", "/etc/gofer.json","-v", "debug", "agent" ]
    network_mode: "host"
    volumes:
      - "./config/gofer.json:/etc/gofer.json"

  spire_feed1:
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    container_name: spire_feed1.local
    entrypoint: [ "/usr/local/bin/spire" ]
    command: [ "-c", "/etc/spire.json", "agent", "-v", "info" ]
    volumes:
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"
      - "./config/spire1.json:/etc/spire.json"
  spire_feed2:
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    container_name: spire_feed2.local
    entrypoint: [ "/usr/local/bin/spire" ]
    command: [ "-c", "/etc/spire.json", "agent", "-v", "info" ]
    volumes:
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"
      - "./config/spire2.json:/etc/spire.json"
  spire_feed3:
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    container_name: spire_feed3.local
    entrypoint: [ "/usr/local/bin/spire" ]
    command: [ "-c", "/etc/spire.json", "agent", "-v", "info" ]
    volumes:
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"
      - "./config/spire3.json:/etc/spire.json"

  spire_feed4:
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    container_name: spire_feed4.local
    entrypoint: [ "/usr/local/bin/spire" ]
    command: [ "-c", "/etc/spire.json", "agent", "-v", "info" ]
    volumes:
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"
      - "./config/spire4.json:/etc/spire.json"
  spire_feed5:
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    container_name: spire_feed5.local
    entrypoint: [ "/usr/local/bin/spire" ]
    command: [ "-c", "/etc/spire.json", "agent", "-v", "info" ]
    volumes:
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"
      - "./config/spire5.json:/etc/spire.json"        
  spire_relay:
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: spire_relay.local
    network_mode: "host"
    entrypoint: [ "/usr/local/bin/spire" ]
    command: [ "-c", "/etc/spire.json", "agent", "-v", "info" ]
    volumes:
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"
      - "./config/spire_relay.json:/etc/spire.json"

  omnia_feed1:
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"

      - "./config/omnia_feed1.json:/home/omnia/omnia.json"
      - "./config/spire1.json:/home/omnia/spire.json"
      - "./config/gofer.json:/home/omnia/gofer.json"

      - "/home/admin/.ethereum/keystore/:/home/omnia/.ethereum/keystore/"
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"

    environment:
      OMNIA_VERBOSE: "true"
      gofer: "/usr/local/bin/gofer"

  omnia_feed2:
    depends_on:
      - gofer
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"

      - "./config/omnia_feed2.json:/home/omnia/omnia.json"
      - "./config/spire2.json:/home/omnia/spire.json"
      - "./config/gofer.json:/home/omnia/gofer.json"

      - "/home/admin/.ethereum/keystore/:/home/omnia/.ethereum/keystore/"
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"

    environment:
      OMNIA_VERBOSE: "true"
      gofer: "/usr/local/bin/gofer"
  omnia_feed3:
    depends_on:
      - gofer
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"

      - "./config/omnia_feed3.json:/home/omnia/omnia.json"
      - "./config/spire3.json:/home/omnia/spire.json"
      - "./config/gofer.json:/home/omnia/gofer.json"

      - "/home/admin/.ethereum/keystore/:/home/omnia/.ethereum/keystore/"
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"

    environment:
      OMNIA_VERBOSE: "true"
      gofer: "/usr/local/bin/gofer"

  omnia_feed4:
    depends_on:
      - gofer
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"
      - "./config/omnia_feed4.json:/home/omnia/omnia.json"
      - "./config/spire4.json:/home/omnia/spire.json"
      - "./config/gofer.json:/home/omnia/gofer.json"
      - "/home/admin/.ethereum/keystore/:/home/omnia/.ethereum/keystore/"
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"

    environment:
      OMNIA_VERBOSE: "true"
      gofer: "/usr/local/bin/gofer"


  omnia_feed5:
    depends_on:
      - gofer
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"
      - "./config/omnia_feed5.json:/home/omnia/omnia.json"
      - "./config/spire5.json:/home/omnia/spire.json"
      - "./config/gofer.json:/home/omnia/gofer.json"
      - "/home/admin/.ethereum/keystore/:/home/omnia/.ethereum/keystore/"
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"

    environment:
      OMNIA_VERBOSE: "true"
      gofer: "/usr/local/bin/gofer"


  omnia_relay:
    depends_on:
      - spire_relay
    # image: omnia_omnia_relay:latest
    build:
      context: "."
      dockerfile: "Dockerfile"
    network_mode: "host"
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"

      - "../dapptools/src/seth/:/opt/seth/"

      - "./config/omnia_relay.json:/home/omnia/omnia.json"
      - "./config/spire_relay.json:/home/omnia/spire.json"
      - "/home/admin/.ethereum/keystore/:/home/omnia/.ethereum/keystore/"
      - "/home/admin/.ethereum/keystore/:/home/admin/.ethereum/keystore/"
    environment:
      OMNIA_VERBOSE: "true"
#      OMNIA_LOG_FORMAT: "json"
networks:
  default:
    name: omnia_network
