name: Omnia Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: .github/docker-compose-unit-tests.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unit Tests
        run: docker-compose -f $COMPOSE_FILE run --rm omnia_unit_tests

  test-e2e:
    name: E2E tests
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: PreBuild Base Omnia images (Remove after PR merge)
        run: docker build -t ghcr.io/chronicleprotocol/base:latest -f docker/base/Dockerfile .
      - name: PreBuild Omnia images (Remove after PR merge)
        run: docker build -t ghcr.io/chronicleprotocol/omnia_dev:latest -f docker/omnia/Dockerfile .
      - name: Start Smocker instance for testing
        run: docker run -d -p 8080:8080 -p 8081:8081 --name smocker thiht/smocker
      - name: Build E2E Tests in Docker
        run: docker build -t omnia_e2e -f test/e2e/Dockerfile .
      - name: Run E2E Test
        run: docker run -i --rm --link smocker omnia_e2e